#!/bin/bash
NS=""
PARAMS=""
while (( "$#" )); do
  case "$1" in
    -n|--namespace)
      NS="-n $2"
      shift 2
      ;;
    -a|--all-namespaces)
      NS="--all-namespaces"
      shift
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"

kubectl get $(kubectl api-resources --verbs=list -o name | paste -sd, -) --ignore-not-found --show-kind -o wide $NS

